# Generated by Django 5.1.6 on 2025-11-16 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication_usertype', '0001_initial'),
        ('company_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='applied_jobs',
            field=models.ManyToManyField(blank=True, related_name='candidates_applied', to='company_dashboard.jobposting'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expertassignment',
            name='assigned_expert',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'EXPERT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Expert User'),
        ),
        migrations.AddField(
            model_name='expertassignment',
            name='company',
            field=models.ForeignKey(limit_choices_to={'role': 'COMPANY'}, on_delete=django.db.models.deletion.CASCADE, related_name='expert_invitations_sent', to=settings.AUTH_USER_MODEL, verbose_name='Assigning Company'),
        ),
        migrations.AddField(
            model_name='expertassignment',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_assignments', to='company_dashboard.jobposting', verbose_name='Job Posting'),
        ),
        migrations.AlterUniqueTogether(
            name='expertassignment',
            unique_together={('job_posting', 'expert_email')},
        ),
    ]
