# Generated by Django 5.1.1 on 2025-01-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_usertype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertassignment',
            name='job_posting',
            field=models.CharField(max_length=255),
        ),
        migrations.RenameField(
            model_name='expertassignment',
            old_name='assigned_on',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='type_of_business',
        ),
        migrations.DeleteModel(
            name='JobPost',
        ),
    ]
