# Generated by Django 5.1.6 on 2025-04-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_usertype', '0002_alter_expertassignment_job_posting_and_more'),
        ('company_dashboard', '0003_jobposting_minimum_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='applied_jobs',
            field=models.ManyToManyField(blank=True, related_name='candidates_applied', to='company_dashboard.jobposting'),
        ),
    ]
