# Generated by Django 5.1.6 on 2025-04-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='minimum_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
