# Generated by Django 5.1.6 on 2025-04-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_dashboard', '0002_alter_jobposting_minimum_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='minimum_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
